name: Test

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run Clippy
        run: just lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: just test

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: just check

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: just format

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: just coverage
